export default class MoviesSchema {
	static schema = {
		name: 'Movies',
		primaryKey: 'id',
		properties: {
			id: { type: 'string', indexed: true },
			title: 'string',
			year: 'string',
			rated: 'string',
			released: 'string',
			runtime: 'string',
			genre: 'string',
			director: 'string',
			writer: 'string',
			actors: 'string',
			plot: 'string',
			language: 'string',
			country: 'string',
			awards: 'string',
			poster: 'string',
			internet_movie_database: 'string?',
			rotten_tomatoes: 'string?',
			metacritic: 'string?',
			metascore: 'string',
			imdbRating: 'string',
			imdbVotes: 'string',
			type: 'string',
			total_seasons: 'string?',
			dvd: 'string?',
			box_office: 'string?',
			production: 'string?',
			website: 'string',
			favorite: 'bool',
		}
	}
}
